---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: "Get timestamp for docker tag"
    shell: "(date +%Y%m%d%H%M%S)"
    register: tag
  - name: Print tag
    debug:
      var: tag

  - name: Setup Docker buildx
    shell: |
      docker buildx create --use --name multiarch --driver docker-container || true
      docker buildx inspect --bootstrap

  - name: Build and push api-service container image with buildx
    shell: |
      docker buildx build \
        --platform linux/amd64 \
        --tag gcr.io/{{ gcp_project }}/llm-rag-analysis-api-service:{{ tag.stdout}} \
        --push \
        /api-service

  - name: Build and push frontend container image with buildx
    shell: |
      docker buildx build \
        --platform linux/amd64 \
        --tag gcr.io/{{ gcp_project }}/llm-rag-analysis-frontend-ai-chatbot:{{ tag.stdout}} \
        --push \
        /frontend-ai-chatbot

  - name: "Save docker tag"
    shell: echo {{ tag.stdout}} > docker-tag
  - name: "Remove all unused containers"
    shell: docker system prune -a
